version: '3.8'

services:
  zhenxun_bot:
    # build: ./zhenxun_bot/Dockerfile
    # image: hsmk/zhenxun_bot_docker:latest
    container_name: zhenxun_bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 超级用户配置
      - SUPERUSERS=["123456"]
      # PostgreSQL 数据库配置
      - DB_URL=postgres://zhenxun:zhenxun_password@postgres:5432/zhenxun
      # 服务配置
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      # 数据持久化
      - ./data:/app/zhenxun_bot/data
      - ./resources:/app/zhenxun_bot/resources
      - ./log:/app/zhenxun_bot/log
      - ./plugins:/app/zhenxun_bot/zhenxun/plugins
    networks:
      - zhenxun_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: zhenxun_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zhenxun
      POSTGRES_USER: zhenxun
      POSTGRES_PASSWORD: zhenxun_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zhenxun_network
    ports:
      - "5432:5432"

networks:
  zhenxun_network:
    driver: bridge

volumes:
  postgres_data: 