version: '3.8'

services:
  zhenxun_bot:
    # build: ./zhenxun_bot/Dockerfile
    # image: hsmk/zhenxun_bot_docker:latest
    container_name: zhenxun_bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 超级用户配置
      - SUPERUSERS=["123456"]
      # MySQL 数据库配置
      - DB_URL=mysql://zhenxun:zhenxun_password@mysql:3306/zhenxun
      # 服务配置
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      # 数据持久化
      - ./data:/app/zhenxun_bot/data
      - ./resources:/app/zhenxun_bot/resources
      - ./log:/app/zhenxun_bot/log
    networks:
      - zhenxun_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: zhenxun_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zhenxun
      MYSQL_USER: zhenxun
      MYSQL_PASSWORD: zhenxun_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zhenxun_network
    ports:
      - "3306:3306"

networks:
  zhenxun_network:
    driver: bridge

volumes:
  mysql_data: 